### PR TITLE
support mocking internal modules like "fs"

### LINKED ISSUE #34: ESM support does not appear to work with "bare" imports
This is my first time using quibble (testdouble, actually, but I think I've tracked the problem here), so it's quite possible that I'm misunderstanding something about the way things are supposed to work.  If I'm understanding correctly, however, there's something in the "bare specifier" import case that's not quite working.  I have a minimal repro at https://github.com/JaredReisinger/quibble-repro, where `npm run start` shows the normal, non-quibble behavior, and `npm run repro` shows the quibble-wrapped behavior.  As you can see, the quibble-replacement of the local import works as expected, but the quibble-replacement of "fs" (a bare specifier) does not.

This was repro'd on node 14.5.0.

##### `npm run start` _(no replacements are expected)_

```plain
> quibble-repro@0.0.1 start /home/jared/src/JaredReisinger/quibble-repro
> node ./index.mjs

This is main...
Apparently, replaceMe was not replaced!

from README:
------------
# quibble-repro

minimally reproduce a quibble replaceEsm problem

(If you see this from `npm run repro`, that's the problem!)
------------
```

##### `npm run repro` _(both replacements are expected, only the local one actually happens)_

```plain
> quibble-repro@0.0.1 repro /home/jared/src/JaredReisinger/quibble-repro
> node --loader=quibble ./repro.mjs

(node:5729) ExperimentalWarning: --experimental-loader is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)

This is main...
a local import was properly replaced

from README:
------------
# quibble-repro

minimally reproduce a quibble replaceEsm problem

(If you see this from `npm run repro`, that's the problem!)
------------
```

Following the advice from [testdouble wiki's "Don't mock what you don't own"](https://github.com/testdouble/contributing-tests/wiki/Don%27t-mock-what-you-don%27t-own) page, I might simply wrap the external/bare import with a local shim/facade so that I can replace the shim instead.  That feels a little "unnecessarily boilerplate-y" for my particular use-case, but it's doable.  Still, I wanted to pass this along just in case the repro _should_ be something that should work.

### PR DESCRIPTION
**Pull request by giltayar**
Fixes #34

### CODE REVIEW

**Comment by giltayar** [comment]
@searls as usual: once you publish this, don't forget to update testdouble.js and publish it too.

**Comment by searls** [comment]
Wow this change was more involved than I expected, but I appreciate you extracting some functions instead of adding to the method

**Comment by searls** [comment]
Landed in 0.6.4

**Comment by searls** [comment]
And testdouble@3.16.1

**Pull request merged**
