### PR TITLE
Fix obsolote ESM loader

### PR DESCRIPTION
**Pull request by anonrig**
This pull request updates internal dependencies and fixes the bug regarding https://github.com/testdouble/quibble/issues/52

### CODE REVIEW

**Comment by searls** [comment]
I know @giltayar is working on a similar patch, so I'll leave consideration of this to him

**Comment by giltayar** [comment]
The loader change looks good. Unfortunately, you removed support for the old interface.

If that's OK with you, @anonrig, I prefer the PR I added (https://github.com/testdouble/quibble/pull/54) as it is more minimal and supports all versions of Node.js.

**Comment by anonrig** [comment]
Hi @giltayar Your PR looks good (better than mine with backward compatibility). Can we add the other things I've updated to the changeset? Or I can update my PR with your changes

**Comment by giltayar** [comment]
Thanks @anonrig. Would love to look at the other things. I would really love to get this fix out ASAP, as people are waiting for it, so a separate PR with your other changes would be a better fit

@searls

**Pull request closed without merging**
