### PR TITLE
fix #496: remove recursive call to "nextLoad"

### PR DESCRIPTION
**Pull request by giltayar**

### CODE REVIEW

**Comment by giltayar** [comment]
This fixes https://github.com/testdouble/testdouble.js/issues/496

**Comment by giltayar** [comment]
This also surfaced a bug in `ts-node/esm`, so I'll send them a PR.

**Comment by searls** [comment]
Is a test feasible? Is there anything to do before merge?

**Comment by giltayar** [comment]
@searls I know! I usually don't add stuff without a test. But it's just too complicated. The recursion there in the loader hooks is too mind-boggling for me to fully understand. I tried, but just couldn't figure out how to distill the problem into a test. Mostly because I don't know exactly what happened there.

What I _do_ know, is that now quibble's loader code is according to the loader spec, which it wasn't beforehand, so it's a good and proper change.

(Sorry, should have written all this in the PR description)

**Comment by searls** [comment]
Hey @giltayar, I invited you as a maintainer on the npm package (you already have commit bit to the repo). Here's a [release doc](https://github.com/testdouble/quibble/blob/main/RELEASE.md). Want to try cutting this as a release?

**Comment by giltayar** [comment]
Hey @searls. I got the invite, but then I had trouble logging in to NPM (would you believe that?!). Support took some time to figure it out, but by that time, the invite expired. Could you resend?

(and thank you)

**Comment by searls** [comment]
@giltayar cancelling the invite from the npm interface, of course, failed. It did let me re-send it, apparently? Let me know if that works—otherwise I will also need to contact support

**Comment by giltayar** [comment]
It worked!

**Pull request merged**
