### PR TITLE
fix esm mocks on windows

### PR DESCRIPTION
**Pull request by connorjclark**
ref https://github.com/testdouble/testdouble.js/issues/491

Note: I am away from my windows machine so this is not yet verified. How can I configure the travis yml to run the tests on windows?

### CODE REVIEW

**Comment by connorjclark** [comment]
Managed to get the tests to run on windows. Added a script `win:test:esm`. But does require one small change in a dep:

image

**Comment by searls** [comment]
Thanks for continuing to work on this, I appreciate it. I won't be able to review for four or five days so feel free to keep pulling at this and polishing it

**Comment by connorjclark** [comment]
My plan at the moment is to first try it out on our Lighthouse unit tests on Window, but I've got a few more things to do first before I'll be able to try that. I'll comment here when I've verified it works on a big set of tests, so I'd hold off on your own verification until then.

**Comment by searls** [comment]
Hi @connorjclark, this was fixed in v0.6.16 thanks to @webstech's help! https://github.com/testdouble/quibble/pull/89#issuecomment-1427049176

**Pull request closed without merging**
